// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIi3ilpsEmjnIeQk8IdhumpN61cbm95bc',
    appId: '1:769153751748:web:9eaae3784a645e0e764791',
    messagingSenderId: '769153751748',
    projectId: 'crud-d199c',
    authDomain: 'crud-d199c.firebaseapp.com',
    storageBucket: 'crud-d199c.appspot.com',
    measurementId: 'G-NF0L83ZHZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3fOXS7g2wHoPuP62qfUfjKYJGrNg6Og',
    appId: '1:769153751748:android:a46d6dfb32a16dec764791',
    messagingSenderId: '769153751748',
    projectId: 'crud-d199c',
    storageBucket: 'crud-d199c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqYBO7rcCIKn7rJHCV8QbTLwrainRiR8',
    appId: '1:769153751748:ios:d188a734328e908d764791',
    messagingSenderId: '769153751748',
    projectId: 'crud-d199c',
    storageBucket: 'crud-d199c.appspot.com',
    iosClientId: '769153751748-ace3pg2tmh1ik8tibq5ohb7emed9coor.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXqYBO7rcCIKn7rJHCV8QbTLwrainRiR8',
    appId: '1:769153751748:ios:d188a734328e908d764791',
    messagingSenderId: '769153751748',
    projectId: 'crud-d199c',
    storageBucket: 'crud-d199c.appspot.com',
    iosClientId: '769153751748-ace3pg2tmh1ik8tibq5ohb7emed9coor.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
